/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;


import graph.type.Graph;

public class GraphApp {
    public static void main(String[] args) {
        System.out.println("helloooooo");

        Graph graph = new Graph();
        graph.addVertex("Series");
        graph.addEdge("Rick", "Morty");
        System.out.println(graph);

    }
}
