/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.data.Edge;
import graph.data.Vertex;
import graph.type.Graph;

public class GraphApp {
    public static void main(String[] args) {
        System.out.println("helloooooo لا تستحي من براء بليز");

        Graph graph = new Graph();
        Vertex vertex = new Vertex(1);
        Edge edge = new Edge(vertex , 3);
        graph.addNode(vertex);

        System.out.println(graph);

    }
}
